
TEST_OBJS += $(if $(CONFIG_TEST), test/window.o)

TEST2_OBJS += test/format.o
TEST2_OBJS += $(if $(CONFIG_TEST), test/preset.o)
TEST2_OBJS += $(if $(CONFIG_DMD),test/swtest.o)
TEST2_OBJS += $(if $(CONFIG_DMD),test/dmdtest.o)
TEST2_OBJS += test/adjust.o
TEST2_OBJS += test/histogram.o
TEST2_OBJS += test/timestamp.o
TEST2_OBJS += test/stress.o
TEST2_OBJS += $(if $(CONFIG_TEST), test/wire.o)
TEST2_OBJS += test/pricing.o
TEST2_OBJS += test/burnin.o
