#!/bin/sh

##########################################################################
#
# This script automates the process of building all variations of
# FreeWPC in a clean work area.

# Author: Brian Dominy
# Started on November 3, 2007 (adapted from similar GCC6809 script)
#
##########################################################################


# The root of the SVN server that is hosting the files
urlroot=http://www.oddchange.com/svn/public

# The local directory in which files should be checked out
# bldroot will be updated below once the correct branch is known.
bldroot=/home/autobuild/freewpc

# The default SVN branches to check out.
branch="branches/brian"

# Parse command-line options
while [ "x$1" != "x" ]; do
	arg=$1; shift; case $arg in
		-h)
			echo ""
			echo "-k                        Keep files; don't extract"
			echo ""
			echo "Files are extracted from  : $urlroot"
			echo "Files are compiled under  : $bldroot"
			echo ""
			exit 0
			;;
		-bldroot)
			# Override the base bldroot
			bldroot=$1; shift
			;;
		-k*|--noextract)
			# Keep existing sources; don't extract.
			noextract=y
			;;
		*)
			echo "Error: invalid option $1"
			exit 1
	esac
done

# Various directories, autocalculated from the selected branches,
# the server root, and the client root (bldroot).  Do not change
# these!

urlroot="$urlroot/freewpc/$branch"
bldroot="$bldroot/$branch"
log="$bldroot/autobuild.log"
tmpdir="$bldroot/tmp"



extract() {
	# TODO : if files are already extracted, then do an update
	# rather than a checkout
	if [ "$noextract" != "" ]; then 
		doit echo "Skipping extraction from $1"
		return 0
	fi

	echo "Extracting $1 -> $2"
	rm -rf $2
	svn co $1 $2
	return $?
}

mkdir -p $tmpdir
rm -f $log

########### Build FreeWPC ##################

extract $urlroot $bldroot
cd $bldroot && ./stressbuild
