#!/bin/sh
#
# stressbuild - test many different build configurations at once
#

machines="t2 tz wcs afm tester"
native_options="n y"
gcc_options="4.2.3 4.3.2 4.3.3 4.4.0"

case $1 in
	--native)
		native_options="y"
		;;
	--fast)
		native_options="n"
		gcc_options="4.4.0"
		;;
esac

rm -f stressbuild.log
for native in $native_options; do
	if [ "$native" = "y" ]; then
		NATIVE=y; export NATIVE
	else
		unset NATIVE
	fi
	for mach in ${machines}; do
		for debugger in `echo y n`; do
			if [ "$native" = "n" ]; then
				gcctargets=${gcc_options}
			else
				gcctargets=`echo nop`;
			fi
			for gcc in $gcctargets; do
				if [ "$gcc" = "nop" ]; then gcc=; fi
				for target in `echo clean default_target`; do

					cfg="NATIVE=$NATIVE MACHINE=$mach FREEWPC_DEBUGGER=$debugger GCC_VERSION=$gcc target=$target"
					echo "Begin: $cfg" | tee -a stressbuild.log

					export MACHINE=$mach
					export FREEWPC_DEBUGGER=$debugger
					export GCC_VERSION=$gcc
					make -j3 $target 2>&1 >> stressbuild.log
					rc="$?"

					if [ -f err ]; then
						echo "Error file:" | tee -a stressbuild.log
						cat err | tee -a stressbuild.log
					fi
					echo "End: $cfg" | tee -a stressbuild.log
					echo "Exit code: $rc" | tee -a stressbuild.log
					if [ "$rc" != "0" ]; then
						exit $rc
					fi
				done
			done
		done
	done
done
echo "All done".
exit 0
