#!/bin/sh
#
# Copyright 2006 by Brian Dominy <brian@oddchange.com>
#
# This file is part of FreeWPC.
#
# FreeWPC is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# FreeWPC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with FreeWPC; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# ------------------------------------------------------------------
# xbmproto - generate prototype from XBM file
# ------------------------------------------------------------------
# This script generates the 'xbmproto' file, normally named
# 'include/xbmproto.h', which is a set of externs of all the XBM
# images that are found in the specified files.
#

xbmfiles=
outfile=`tty`

function do_proto1 () {
	xbmfile=$1;
	grep bits $xbmfile | sed -e "s/static/extern/" -e "s/=.*$/;/";
	return 0;
}

while [ "$1" != "" ]; do
	arg=$1; shift
	case $arg in
		-f)
			xbmfiles="$xbmfiles $1"; shift
			;;
		-D)
			add=`ls -1 $1/* | grep ".xbm"`
			xbmfiles="$xbmfiles $add"
			shift
			;;
		-o)
			outfile=$1; shift
			;;
	esac
done

echo "#ifndef _XBMPROTO_H" > $outfile
echo "#define _XBMPROTO_H" >> $outfile
(
for xbm in $xbmfiles; do
	do_proto1 $xbm;
done
) >> $outfile
echo "#endif // _XBMPROTO_H" >> $outfile

