#!/bin/sh

# The first time you build, you need to specify 'unpack' to extract
# the main gcc sources, and then 'patch' to apply a patch that tells
# the compiler about our new target.  Thereafter just run this script
# to build and install the compiler.
#

# After unpacking 4.0.1, you need to set up the symbolic link to force
# the m6809 config files into being.


VERSION=3.1.1

whereis sudo >/dev/null 2>&1
if [ "$?" = "0" ]; then
	SUDO=sudo
fi

while [ "$1" != "" ]; do
arg=$1; shift
case $arg in
	ver4)
		VERSION=4.0.1
		;;
	
	# I'm not using the Thomson assembler anymore ... I use
	# the latest version of asxxxx tools.
	asm)
		# cd .. && zcat asm-6809.tar.gz | tar xvf -
		cd ../asm-thomson && make clean && make && $SUDO make install
		;;

	unpack)
		cd .. && bzcat gcc-${VERSION}.tar.bz2 | tar xvf -
		;;

	patch)
		# This patch file only works for gcc 3.1.1
		# - add m6809 into config.sub
		# - add m6809-* into config.gcc
		# - add m6809-*-*) tm_file=m6809/m6809.h in config.gcc also
		cd .. && patch -p0 < m6809-gcc.diff
		# TODO : copy all files from ROOT/gcc-patch into ROOT/gcc-3.1.1/gcc
		;;

	config|configure)
		../gcc-${VERSION}/configure --target=m6809 --program-suffix=09 --nfp --enable-obsolete
		;;

	clean)
		make clean LANGUAGES="c proto c++"
		;;

	*)
		make cross LANGUAGES="c proto c++"
		cd gcc && $SUDO make LANGUAGES="c proto c++" install
		echo "Copying new executable ... installation complete!"
		$SUDO mkdir -p /usr/local/m6809/bin
		$SUDO cp xgcc /usr/local/m6809/bin/gcc
		echo "Done building"
		;;
esac
done

