#!/usr/bin/perl

my @sectionNumbers = ( 1, 1, 1, 1, 1, 1, 1 );
my $sectionLevel = -1;
my $inParagraph = 0;
my $inList = 0;
my $urlRoot = "http://www.oddchange.com";
my $fileRoot = "http://www.oddchange.com/svn/public/freewpc/trunk";
my $apiRoot = "http://www.oddchange.com/freewpc/doc/html";
my $docTitle = "FreeWPC Programmer's Reference";
my $currentDate = `date`;
my $inputFile = "master.g";
my $outputFile = "index.html";
my $tocFlag = 0;

my $headingTopMargin = ($tocFlag ? "0px" : "8px");
my $headingBottomMargin = ($tocFlag ? "0px" : "8px");
my $headingWeight = ($tocFlag ? "normal" : "bold");
my $indentation = "20px";

my $cssDecl = <<END;
<style type="text/css" media="screen">
body { margin-left: 10%; margin-right: 10% }
h1, h2, h3, h4, h5, h6 { 
	font-size: 16px; 
	font-weight: $headingWeight;
	margin-top: $headingTopMargin;
	margin-bottom: $headingBottomMargin; 
}
.S { padding-left: $indentation; }
</style>
END


sub printHeader
{
	print OFH <<END;
<html>
<head>
<title>$docTitle</title>
$cssDecl
</head>
<body>
<h1>$docTitle</h1>
<p>
<i>Brian Dominy</i><br>
<i>$currentDate</i><br>
</p>
END
}

sub printFooter
{
	print OFH <<END;
</body>
</html>
END
}

sub printParagraphStart
{
	if (!$inParagraph) {
		$inParagraph = 1;
		print OFH "<p>";
	}
}

sub printParagraphEnd
{
	if ($inParagraph) {
		$inParagraph = 0;
		print OFH "</p>";
	}
}

sub printListItemStart
{
	my ($item) = @_;
	printParagraphEnd ();
	if ($inList) {
		print OFH "</li>";
	} else {
		print OFH "<ul>\n";
	}
	$item =~ s/%api\(([^,]*)\)/<a href="$apiRoot\/$1">$1<\/a>/g;
	print OFH "<li>" . $item;
	$inList = 1;
}

sub printListItemEnd
{
	print OFH "</li></ul>\n";
	$inList = 0;
}

sub printSectionLevel
{
	my ($name, $summary) = @_;
	printParagraphEnd ();
	printListItemEnd ();

	print OFH "<h"; print OFH $sectionLevel+1; print OFH ">";
	print OFH "<a href=\"\">" if ($tocFlag);
	print OFH $sectionNumbers[0];
	for (my $i = 1; $i <= $sectionLevel; $i++) {
		print OFH "." . $sectionNumbers[$i];
	}
	print OFH "&nbsp;&nbsp;$name";
	print OFH " ($summary)" if ($summary ne "");
	print OFH "</a>" if ($tocFlag);
	print OFH "</h"; print OFH $sectionLevel+1; print OFH ">";
}

sub printContent
{
	my ($line) = @_;
	return if ($tocFlag);
	if ($line ne "") {
		printParagraphStart ();
		$line =~ s/%tool\((.*)\)/$1/g;
		$line =~ s/%url\((.*)\)/<a href="$urlRoot\/$1">$urlRoot\/$1<\/a>/g;
		$line =~ s/%file\((.*)\)/<a href="$fileRoot\/$1">$1<\/a>/g;
		$line =~ s/%reqdef\((.*)\)/Define this to be $1.  This must be defined./g;
		$line =~ s/%optdef\((.*)\)/This is an optional define.  When set, it indicates $1./g;
		$line =~ s/%def\((.*)\)/Define this to be $1/g;
		$line =~ s/'''([^']*)'''/\<b\>$1\<\/b\>/g;
		$line =~ s/\/\/\/([^\/]*)\/\/\//\<i\>$1\<\/i\>/g;
		print OFH $line . "\n";
	}
	else {
		printParagraphEnd ();
	}
}

sub printLevelStart ()
{
	print OFH "<div class=\"S\">\n" if ($sectionLevel > 0);
}

sub printLevelEnd ()
{
	print OFH "</div>\n" if ($sectionLevel > 0);
}


while ($arg = shift) {
	if ($arg =~ /-o/) {
		$outputFile = shift;
		open OFH, ">$outputFile" or die "Can't open $outputFile: $!\n";
	}
	elsif ($arg =~ /-T/) {
		$tocFlag = 1;
	}
	else {
		$inputFile = $arg;
	}
}


open FH, $inputFile or die "Can't open $inputFile: $!\n";
printHeader ();
while (<FH>)
{
	chomp;
	$_ =~ s/^[ \t]*//;
	next if (/^#/);
	if (/^\{(.*)/) {
		$sectionLevel++;
		my ($name, $summary) = split /:/, $1;
		$summary =~ s/^[ \t]*//;
		printLevelStart ();
		printSectionLevel ($name, $summary); print "\n";
	}
	elsif (/^\}/) {
		printLevelEnd ();
		$sectionNumbers[$sectionLevel + 1] = 1;
		$sectionNumbers[$sectionLevel]++;
		$sectionLevel--;
	}
	elsif (/^\<(.*)/) {
		printListItemStart ($1) if (!$tocFlag);
	}
	elsif (/^\>/) {
		printListItemEnd () if (!$tocFlag);
	}
	elsif (/^!file (.*)/) {
		printContent ("Source files implementing this feature: \%file(kernel/$1)");
	}
	else {
		printContent ($_);
	}
}
printFooter ();
close FH;
close OFH;
