#!/bin/sh
#
# stressbuild - test many different build configurations at once
#

# export mach direct debugger as target

rm -f stressbuild.out
for plat in `echo linux wpc`; do
	for mach in `echo tz wcs afm tester`; do
		for debugger in `echo y n`; do
			for target in `echo clean default_target`; do
				if [ "$plat" = "wpc" ]; then
					gcctargets=`echo 3.4.6 trunk`;
				else
					gcctargets=`echo nop`;
				fi
				for gcc in $gcctargets; do
					if [ "$gcc" = "nop" ]; then gcc=; fi
					echo Execing make \
						PLATFORM=$plat MACHINE=$mach DEBUGGER=$debugger \
						GCC_VERSION=$gcc $target | tee -a stressbuild.out
					make PLATFORM=$plat MACHINE=$mach GCC_VERSION=$gcc \
						DEBUGGER=$debugger $target \
						2>&1 >> stressbuild.out
	          	if [ $? != 0 ]; then exit 1; fi
				done
			done
		done
	done
done
echo "All done".
exit 0
