#!/usr/bin/perl
#
# alphaglob - sorts 6809 function definitions in their assembly form in
# alphabetical order.  Different GCC versions output the assembly for
# a file in different order, which makes diffing between the two difficult.
# This script tries to normalize things.
#

while (<>) {
	chomp;
	s/;.*$//;
	s/L[0-9]+/Lxx/;
	s/LC[0-9]+/LCxx/;

	if (/\.globl (.*)$/) {
		$symbol = $1;
		# $def{$symbol} .= "$1:\n";
	}
	elsif (/[ \t]*\.(byte|word|blkb|module|area|ascii)/) {}
	#elsif (/LC[0-9]+:/) {
	#	$symbol = $_;
	#	$def{$symbol} .= "$_\n";
	#}
	elsif (/^[ \t]*$/) {}
	else {
		$def{$symbol} .= "$_\n";
	}
}

for $symbol (sort (keys %def)) {
	next if $symbol =~ /^[^_]/;
	my @lines = split /\n+/, $def{$symbol};
	for $line (@lines) {
		print "$symbol    --->   $line\n";
	}
	print "\n\n";
}
