#!/bin/sh
# Find files that have committed in 2009.  Then see if their copyright
# headers are up-to-date, and if not, add 2009 to them.

for f in `git ls-files`; do
	when=`git log $f | head -n 5 | grep "^Date:"`
	echo $when | grep "2009" > /dev/null
	if [ "$?" = "0" ]; then
		echo -n "Checking $f ... "
		# Is the 2009 in the copyright header?
		grep "Copyright.*2009" $f > /dev/null 2>&1
		if [ "$?" != "0" ]; then
			# No... how about some copyright statement at least?
			grep "Copyright.*200[5678]" $f > /dev/null 2>&1
			if [ "$?" != "0" ]; then
				echo "No copyright at all!";
			else
				echo "Copyright needs updating";
				sed -i -e "s/\(Copyright 200[5-8]\)-200[5-8]/\1-2009/" \
					-e "s/Copyright 200[ ,0-8]*[0-8]/&, 2009/" $f
				# sed -e "s/\(Copyright 200[5-8]\)-200[5-8]/\1-2009/" \
				#		-e "s/Copyright 200[ ,0-8]*[0-8]/&, 2009/" $f | head -n 10
			fi
		else
			echo "OK";
		fi
	fi
done
