#!/bin/sh
#
# copyright-check
#
# This script should be invoked from the top-level directory; e.g.
# run "tools/copyright-check".
#

touch -t `date +%Y`01010000 tools/copyright-timestamp
for dir in `echo include machine kernel common test tools wpcsound platform`; do
	cd $dir
	# Find all files that have been touched in 2008
	for f in `find . -name "*.[chs]" -newer ../tools/copyright-timestamp`; do
		echo -n "Checking $dir/$f ... "
		# Is the 2008 in the copyright header?
		grep "Copyright.*2008" $f > /dev/null 2>&1
		if [ "$?" != "0" ]; then
			# No... how about some copyright statement at least?
			grep "Copyright.*200[567]" $f > /dev/null 2>&1
			if [ "$?" != "0" ]; then
				echo "No copyright at all!";
			else
				echo "Copyright needs updating";
				sed -i -e "s/Copyright 200[ ,0-9]*[0-9]/&, 2008/" $f
				# sed -i -e "s/Copyright 200/&, 2008/" $f
			fi
		else
			echo "OK";
		fi
	done
	cd ..
done
rm -f tools/copyright-timestamp
