#!/bin/sh
# Find files that have committed in 2009.  Then see if their copyright
# headers are up-to-date, and if not, add 2009 to them.

for f in `git ls-files`; do

	# Skip files that don't need a copyright statement.
	case "$f" in
		*.fon|*.xbm|*.png|*.jpg|*.xbm|*.zip|*.ttf)
			continue
			;;
	esac

	echo -n "Checking $f ... "
	# If the header already includes the latest year, nothing to do.
	grep -m 1 "Copyright.*2009" "$f" > /dev/null 2>&1
	if [ "$?" != "0" ]; then
		# Hmm, this file might need updating.

		# Get the time that the file was last modified and committed.
		when=`git log --no-renames -n 1 "$f" | grep -m 1 "^Date:"`
		# See if it was updated in 2009.
		echo $when | grep -m 1 "2009" > /dev/null
		if [ "$?" = "0" ]; then

			# Yes, it has changed and 2009 isn't in the header...
			# Is there at least some copyright statement?
			grep -m 1 "Copyright.*200[5678]" "$f" > /dev/null 2>&1
			if [ "$?" != "0" ]; then
				echo "No copyright at all!";
			else
				echo "Copyright needs updating";
				if [ "$1" != "-p" ]; then
					sed -i -e "s/\(Copyright 200[5-8]\)-200[5-8]/\1-2009/" \
						-e "s/Copyright 200[ ,0-8]*[0-8]/&, 2009/" "$f"
				fi
			fi
		else
			echo "OK"
		fi
	else
		echo "OK"
	fi
done
