#!/usr/bin/perl
#
# Copyright 2006 by Brian Dominy <brian@oddchange.com>
#
# This file is part of FreeWPC.
#
# FreeWPC is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# FreeWPC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with FreeWPC; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# ------------------------------------------------------------------
# gendefine - generate include files of #defines automatically
# ------------------------------------------------------------------
# Scan all source files recursively and grep them for
# defines that match a particular pattern.  For each
# one, generate a unique value for it.
#

my $prefix = "GID_";

my @dirs = (
	"include", 
	"include/sys", 
	"include/mach", 
	"kernel", 
	"mach", 
	"fonts", 
	"test"
	);

my $firstval = 1;



my @defines = ();

my %definehash;

my $nextval = $firstval;

while ($arg = shift)
{
	if ($arg =~ m/-p/) {
		$prefix = shift;
	}
}

foreach $dir (@dirs) {
	my @files = split /\n+/, 
		`cd $dir && find . -maxdepth 1 -name "*.[ch]"`;
	foreach $file (@files) {
		push @srclist, "$dir/" . $file;
	}
}

foreach $src (@srclist) {
	# print "Processing $src:\n";
	open FH, $src;
	while (<FH>) {
		chomp;
		if (/[^a-zA-Z0-9_](${prefix}[a-zA-Z0-9_]*)/) {
			my $define = $1;
			# print "Found $define.\n";
			if (!defined $definehash{$define})
			{
				push @defines, $define;
				$definehash{$define} = $nextval;
				$nextval++;
			}
		}
	}
	close FH;
}

print "#ifndef __GENDEFINE_" . $prefix . "\n";
print "#define __GENDEFINE_" . $prefix . "\n";
foreach $define (@defines) {
	print "#define $define " . $definehash{$define} . "\n";
}
print "#endif /* __GENDEFINE_" . $prefix . " */\n";

