#!/bin/bash
#
# pagemap

while [ "$1" != "" ]; do
	arg=$1; shift
	case $arg in
		-listtype)
			filetype=$1; shift
			if [ "$1" = "-aso" ]; then
				converter=`echo sed -e "s/\..*$/.o/"`
			else
				converter="cat"
			fi
			grep -o "^.*\.${filetype}" $mapfiles | $converter
			;;
		-getpage)
			filename=$1; shift
			section=`grep "^${filename}" $mapfiles | awk '{print $2}'`
			page=`grep "^page.*:" $mapfiles | grep $section | awk '{print $1}' | sed -e "s/:$//"`
			echo Section is $section
			echo Page is $page
			;;
		-listpage)
			page=$1; shift
			sections=`grep "^${page}:" $mapfiles | awk '{print $2, $3, $4, $5, $6, $7, $8}'`
			echo $sections
			;;
		-listsection)
			section=$1; shift
			if [ "$1" = "-aso" ]; then
				converter=`echo sed -e "s/\..*$/.o/"`
			else
				converter="cat"
			fi
			grep "^[^:]* ${section}$" $mapfiles | awk '{print $1}' | $converter
			;;
		-*)
			;;
		*)
			mapfiles="$mapfiles $arg"
			;;
	esac
done
